dbt_project:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: 192.168.1.101
      port: 5432
      user: user
      pass: password123
      dbname: warehouse
      schema: staging

  target: dev
